1.19.3
Technici4n/Modern-Dynamics pull request #56
Opened 2022-12-26 05:28 UTC by BonbonGit

Tried to port to 1.19.3

I have honestly no idea what I am doing and just tried to find equivalent classes/methods in the new versions of Fabric and Minecraft.

Which results in missing textures for pipes for now, but otherwise the mod seems to work.

Also you may want to merge it in another branch since I don't think build for 1.19.3 can be made compatible with older versions.

2022-12-26 09:13 UTC, Technici4n requested changes
Looks like a good start, thank you. For the creative tab: tabs are now directly responsible for their contents. For MD the registration order is fine: we can simply add all Item registry entries that live in the MD namespace.

2022-12-26 09:13 UTC, Technici4n commented on src/client/java/dev/technici4n/moderndynamics/client/model/PipeUnbakedModel.java
> +                // Load transform from the vanilla block model
Why?

2022-12-26 09:14 UTC, Technici4n commented
Oh, and you need to run `gradlew runData` to generate some models, the recipes, the attachment upgrades, etc...

2022-12-26 23:44 UTC, BonbonGit commented
> Looks like a good start, thank you. For the creative tab: tabs are now directly responsible for their contents. For MD the registration order is fine: we can simply add all Item registry entries that live in the MD namespace.

Added items to the creative tab. Not sure that's how you meant to do it but it works.

> Oh, and you need to run `gradlew runData` to generate some models, the recipes, the attachment upgrades, etc...

I get recipes, upgrades, etc. now and from what I understand models load too but not textures:

![image](https://user-images.githubusercontent.com/33197817/209588507-02660218-9a88-4eb1-a652-76e51f4c0777.png)

But I don't undestand what is supposed to load the textures so I'm stuck here.

2022-12-27 20:52 UTC, BonbonGit commented on src/client/java/dev/technici4n/moderndynamics/client/model/MdModels.java
> +        Transformation preRotation = new Transformation(null, new Quaternionf(0, 0, 1, 0), null, null);
Sorry I'm clueless about geometry so I have no idea what the line previously there or what I replaced it with does, but it works somehow.

2022-12-28 00:38 UTC, Technici4n commented
Thanks a lot, I'll have a look in a few days. I have another feature in the pipeline that I want done before I merge this.

2023-04-18 17:33 UTC, ewpratten commented
Hey, just hopping in to say that I have been running this branch on a small server for a few days, and everything works great!

2023-04-19 06:09 UTC, Technici4n commented
Good to know. However there won't be any official 1.19.3 release, and I'm waiting on 1.20 instead.

2023-09-20 09:49 UTC, closed without merging